spring:
  profiles:
    active: "dev-postgres"
  main:
    banner-mode: "off"
debug: true
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
---
spring:
  config:
    activate:
      on-profile: dev-postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://pg.micakovic.at:5432/tradecool
    username: ReactSpringSecUserServices
    password: ZAjzkIXjQMIvWa5v
#    url: jdbc:postgresql://localhost:5432/tradecool
#    username: ika
#    password: 5555
#    driverClassName: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: dev-h2
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:tradecool
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update

---