spring:
  profiles:
    active: "dev-postgres"
  main:
    banner-mode: "off"

---
spring:
  config:
    activate:
      on-profile: dev-postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://pg.micakovic.at:5432/tradecool
    username: ReactSpringSecUserServices
    password: ZAjzkIXjQMIvWa5v
    driverClassName: org.postgresql.Driver
jwt:
  secret: 8dUS5AhkJ81p8TFTRT9O6WuITgthmL3N
---
spring:
  config:
    activate:
      on-profile: dev-h2
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:tradecool
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update
jwt:
  secret: 8dUS5AhkJ81p8TFTRT9O6WuITgthmL3N
---