spring:
  profiles:
    active: "dev-postgres"
  main:
    banner-mode: "off"

---
spring:
  config:
    activate:
      on-profile: dev-postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/tradecool
    username: luk4skoch
    password: 123456
    driverClassName: org.postgresql.Driver


---
spring:
  config:
    activate:
      on-profile: dev-h2
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    url: jdbc:h2:mem:tradecool
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: update

---